import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useSearchParams } from 'react-router-dom'
import { ArrowUpRight, Calculator, CheckCircle2 } from 'lucide-react'
import { SEO } from '../components/SEO'
import { useVehicles } from '../hooks/useVehicles'
import { installment, money, whatsappFor } from '../lib/format'
import { supabase } from '../lib/supabase'
import { site } from '../config/site'
const schema=z.object({
  name:z.string().trim().min(2).max(120),whatsapp:z.string().regex(/^\d{10,15}$/,'Informe DDD e número'),
  email:z.union([z.email(),z.literal('')]).optional(),vehicle_id:z.string().optional(),
  amount:z.number().positive(),down_payment:z.number().min(0),installments:z.number().refine(n=>[12,24,36,48,60].includes(n)),
  consent:z.literal(true,{error:'O consentimento é obrigatório'})
}).refine(v=>v.down_payment<v.amount,{path:['down_payment'],message:'A entrada deve ser menor que o valor do veículo'})
type Values=z.infer<typeof schema>
export default function Finance(){
  const [params]=useSearchParams()
  const {data=[]}=useVehicles()
  const [success,setSuccess]=useState(false)
  const [whatsappUrl,setWhatsappUrl]=useState('')
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const {register,handleSubmit,watch,setValue,formState:{errors}}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{vehicle_id:params.get('veiculo')||'',amount:0,down_payment:0,installments:48}})
  const amount=Number(watch('amount'))||0,down=Number(watch('down_payment'))||0,n=Number(watch('installments'))||48
  const selected=data.find(v=>v.id===watch('vehicle_id'))
  useEffect(()=>{const id=params.get('veiculo');const found=data.find(v=>v.id===id);if(found){setValue('vehicle_id',found.id);setValue('amount',found.price)}},[data,params,setValue])
  const onVehicle=(id:string)=>{setValue('vehicle_id',id);const v=data.find(x=>x.id===id);if(v)setValue('amount',v.price)}
  const submit=async(v:Values)=>{if(busy)return;setBusy(true);setError('');try{const vehicle=data.find(x=>x.id===v.vehicle_id);const {error:dbError}=await supabase.from('financing_requests').insert({name:v.name,whatsapp:v.whatsapp,email:v.email||null,vehicle_id:vehicle?.id.startsWith('demo-')?null:vehicle?.id||null,vehicle_text:vehicle?`${vehicle.brand} ${vehicle.model}`:null,amount:v.amount,down_payment:v.down_payment,installments:v.installments,consent:true,contacted:false});if(dbError)throw dbError;const url=whatsappFor(`Olá! Enviei uma solicitação de financiamento para ${vehicle?`${vehicle.brand} ${vehicle.model}`:'um veículo'}, valor ${money(v.amount)}, entrada ${money(v.down_payment)} em ${v.installments} parcelas. Meu nome é ${v.name}.`);setWhatsappUrl(url);setSuccess(true);window.open(url,'_blank','noopener,noreferrer')}catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar.')}finally{setBusy(false)}}
  return <><SEO title="Financie seu veículo" description="Simule o financiamento do seu carro ou moto e fale com a Braza Veículos."/><section className="container-wide pb-24 pt-40"><div className="max-w-3xl"><span className="font-bold uppercase tracking-widest text-primary">Seu próximo passo</span><h1 className="mt-3 text-[2rem] font-extrabold leading-tight sm:text-5xl md:text-6xl">Financiamento facilitado</h1><p className="mt-5 text-lg text-foreground/65">Faça uma estimativa e converse com a nossa equipe sobre as opções para você.</p></div><div className="mt-12 grid gap-8 lg:grid-cols-[1fr_.8fr]"><div className="rounded-3xl border border-border bg-card p-6 md:p-9"><div className="mb-6 flex items-center gap-3"><Calculator className="text-primary"/><h2 className="text-3xl">Simule sua parcela</h2></div><div className="grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Veículo (opcional)</span><select className="field" value={watch('vehicle_id')||''} onChange={e=>onVehicle(e.target.value)}><option value="">Ainda não escolhi</option>{data.map(v=><option key={v.id} value={v.id}>{v.brand} {v.model} · {money(v.price)}</option>)}</select></label><label><span className="label">Valor do veículo (R$)</span><input className="field" type="number" min="0" value={amount||''} onChange={e=>setValue('amount',Number(e.target.value))}/></label><label><span className="label">Entrada (R$)</span><input className="field" type="number" min="0" value={down||''} onChange={e=>setValue('down_payment',Number(e.target.value))}/></label><label className="sm:col-span-2"><span className="label">Parcelas</span><select className="field" value={n} onChange={e=>setValue('installments',Number(e.target.value))}>{[12,24,36,48,60].map(x=><option key={x} value={x}>{x} meses</option>)}</select></label></div><div className="mt-8 rounded-3xl bg-primary/10 p-7"><span className="text-sm">Estimativa de parcela</span><strong className="mt-2 block font-display text-4xl text-primary">{amount>down?money(installment(amount,down,n)):money(0)}<small className="text-base"> / mês</small></strong><p className="mt-3 text-xs text-foreground/65">Taxa ilustrativa de {(site.monthlyInterestRate*100).toFixed(2).replace('.',',')}% ao mês. Esta é apenas uma simulação sem compromisso, sujeita a análise de crédito. Valores finais podem variar.</p></div></div>
  <div className="rounded-3xl bg-muted p-6 md:p-9"><h2 className="text-3xl">Receba atendimento</h2><p className="mt-3 text-foreground/65">Envie seus dados para conversarmos. Não pedimos CPF.</p>{success?<div className="mt-10"><CheckCircle2 size={48} className="text-primary"/><h3 className="mt-4 text-2xl">Solicitação enviada!</h3><p>Entraremos em contato em breve.</p><a href={whatsappUrl} target="_blank" rel="noopener noreferrer" className="btn-primary mt-6">Abrir conversa no WhatsApp</a></div>:<form className="mt-7 space-y-5" onSubmit={handleSubmit(submit)}><label className="block"><span className="label">Nome</span><input className="field" {...register('name')}/>{errors.name&&<small role="alert" className="text-accent">{errors.name.message}</small>}</label><label className="block"><span className="label">WhatsApp com DDD</span><input className="field" inputMode="numeric" {...register('whatsapp')}/>{errors.whatsapp&&<small role="alert" className="text-accent">{errors.whatsapp.message}</small>}</label><label className="block"><span className="label">E-mail (opcional)</span><input className="field" type="email" {...register('email')}/>{errors.email&&<small role="alert" className="text-accent">{errors.email.message}</small>}</label><input type="hidden" {...register('vehicle_id')}/><input type="hidden" {...register('amount',{valueAsNumber:true})}/><input type="hidden" {...register('down_payment',{valueAsNumber:true})}/><input type="hidden" {...register('installments',{valueAsNumber:true})}/><label className="flex items-start gap-3 text-sm"><input type="checkbox" {...register('consent')} className="mt-1"/><span>Concordo com o uso dos meus dados para contato sobre financiamento, conforme a política de privacidade.</span></label>{errors.consent&&<small role="alert" className="text-accent">{errors.consent.message}</small>}{errors.down_payment&&<small role="alert" className="block text-accent">{errors.down_payment.message}</small>}{error&&<p role="alert" className="text-accent">{error}</p>}<button disabled={busy} className="btn-primary w-full disabled:opacity-50">{busy?'Enviando...':'Solicitar contato'} <ArrowUpRight size={18}/></button></form>}{selected&&<p className="mt-5 text-xs text-foreground/55">Veículo selecionado: {selected.brand} {selected.model}</p>}</div></div></section></>
}
