import { useEffect, useState } from 'react'
import { Link, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { Helmet } from 'react-helmet-async'
import { CarFront, ClipboardList, KeyRound, LogOut } from 'lucide-react'
import type { User } from '@supabase/supabase-js'
import { supabase } from '../../lib/supabase'
import AdminVehicles from './AdminVehicles'
import VehicleForm from './VehicleForm'
import Leads from './Leads'
function Login(){const navigate=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const {data:auth,error:authError}=await supabase.auth.signInWithPassword({email,password});if(authError||!auth.user){setError('E-mail ou senha inválidos.');return}const {data:role,error:roleError}=await supabase.from('user_roles').select('role').eq('user_id',auth.user.id).eq('role','admin').maybeSingle();if(roleError||!role){await supabase.auth.signOut();setError(roleError?'Não foi possível verificar sua permissão. Tente novamente.':'Este usuário não tem acesso administrativo.');return}navigate('/admin',{replace:true})}catch{setError('Não foi possível entrar. Tente novamente.')}finally{setBusy(false)}};return <div className="grid min-h-screen place-items-center bg-muted p-4"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-8"><img src="/images/logo-braza.png" alt="Braza Veículos" className="mb-7 h-20"/><h1 className="text-3xl">Acesso administrativo</h1><form onSubmit={submit} className="mt-7 space-y-5"><label className="block"><span className="label">E-mail</span><input className="field" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block"><span className="label">Senha</span><input className="field" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="text-sm text-accent">{error}</p>}<button className="btn-primary w-full" disabled={busy}>{busy?'Entrando...':'Entrar'}</button></form></div></div>}
function ChangePassword(){const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;if(password.length<12||password!==confirm){setMessage('Use pelo menos 12 caracteres e confirme a mesma senha.');return}setBusy(true);try{const {error}=await supabase.auth.updateUser({password});setMessage(error?error.message:'Senha alterada com sucesso.');if(!error){setPassword('');setConfirm('')}}catch{setMessage('Não foi possível alterar a senha.')}finally{setBusy(false)}};return <div className="max-w-lg"><h1 className="mb-7 text-3xl">Alterar senha</h1><form className="space-y-5" onSubmit={submit}><label className="block"><span className="label">Nova senha</span><input type="password" className="field" autoComplete="new-password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="block"><span className="label">Confirmar senha</span><input type="password" className="field" autoComplete="new-password" minLength={12} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>{message&&<p role="status">{message}</p>}<button className="btn-primary" disabled={busy}>{busy?'Salvando...':'Salvar nova senha'}</button></form></div>}
function Guard({user,children}:{user:User|null;children:React.ReactNode}){const [status,setStatus]=useState<'loading'|'allowed'|'denied'>('loading');useEffect(()=>{if(!user){setStatus('denied');return}let active=true;setStatus('loading');supabase.from('user_roles').select('role').eq('user_id',user.id).eq('role','admin').maybeSingle().then(async({data,error})=>{if(!active)return;if(error||!data){await supabase.auth.signOut();if(active)setStatus('denied')}else setStatus('allowed')});return()=>{active=false}},[user]);if(status==='loading')return <div className="skeleton min-h-screen"/>;if(status==='denied')return <Navigate to="/admin/login" replace/>;return <>{children}</>}
function Shell(){const navigate=useNavigate();return <div className="min-h-screen bg-muted"><header className="border-b border-border bg-card"><div className="container-wide flex flex-wrap items-center justify-between gap-4 py-3"><Link to="/admin"><img src="/images/logo-braza.png" alt="Braza Veículos" width="120" height="70" className="h-12 rounded-xl bg-white p-1"/></Link><nav className="flex flex-wrap gap-3 text-sm font-bold"><NavLink to="/admin" end className="btn-outline"><CarFront size={17}/>Veículos</NavLink><NavLink to="/admin/leads" className="btn-outline"><ClipboardList size={17}/>Solicitações</NavLink><NavLink to="/admin/senha" className="btn-outline"><KeyRound size={17}/>Senha</NavLink></nav><button className="btn-outline" onClick={async()=>{await supabase.auth.signOut();navigate('/admin/login')}}><LogOut size={17}/>Sair</button></div></header><main className="container-wide py-10"><Routes><Route index element={<AdminVehicles/>}/><Route path="veiculos/novo" element={<VehicleForm/>}/><Route path="veiculos/:id" element={<VehicleForm/>}/><Route path="leads" element={<Leads/>}/><Route path="senha" element={<ChangePassword/>}/><Route path="*" element={<Navigate to="/admin" replace/>}/></Routes></main></div>}
export default function Admin(){const [user,setUser]=useState<User|null|undefined>(undefined);useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));return()=>subscription.unsubscribe()},[]);return <><Helmet><meta name="robots" content="noindex,nofollow"/></Helmet>{user===undefined?<div className="skeleton min-h-screen"/>:<Routes><Route path="login" element={user?<Navigate to="/admin" replace/>:<Login/>}/><Route path="*" element={<Guard user={user}><Shell/></Guard>}/></Routes>}</>}
