import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { supabase } from '../../lib/supabase'
import { digits } from '../../lib/format'
export default function Leads(){
  const [tab,setTab]=useState<'sell_requests'|'financing_requests'>('sell_requests')
  const [message,setMessage]=useState('')
  const qc=useQueryClient()
  const {data=[],isLoading,error}=useQuery({queryKey:['admin-leads',tab],queryFn:async()=>{
    if(tab==='sell_requests'){const {data,error}=await supabase.from('sell_requests').select('*,sell_request_photos(*)').order('created_at',{ascending:false});if(error)throw error;return data}
    const {data,error}=await supabase.from('financing_requests').select('*').order('created_at',{ascending:false});if(error)throw error;return data
  }})
  const mark=async(id:string,contacted:boolean)=>{const {error}=await supabase.from(tab).update({contacted:!contacted}).eq('id',id);if(error)setMessage(error.message);else qc.invalidateQueries({queryKey:['admin-leads',tab]})}
  const remove=async(id:string)=>{if(!confirm('Excluir esta solicitação?'))return;try{
    if(tab==='sell_requests'){const {data:photos,error:photoError}=await supabase.from('sell_request_photos').select('storage_path').eq('request_id',id);if(photoError)throw photoError;if(photos?.length){const {error:storageError}=await supabase.storage.from('sell-requests').remove(photos.map(p=>p.storage_path));if(storageError)throw storageError}}
    const {error}=await supabase.from(tab).delete().eq('id',id);if(error)throw error;qc.invalidateQueries({queryKey:['admin-leads',tab]})
  }catch(e){setMessage(e instanceof Error?e.message:'Falha ao excluir')}}
  return <><h1 className="mb-6 text-4xl">Solicitações</h1><div className="mb-7 flex gap-3"><button className={tab==='sell_requests'?'btn-primary':'btn-outline'} onClick={()=>setTab('sell_requests')}>Solicitações de venda</button><button className={tab==='financing_requests'?'btn-primary':'btn-outline'} onClick={()=>setTab('financing_requests')}>Solicitações de financiamento</button></div>{message&&<p role="status">{message}</p>}{isLoading?<div className="skeleton h-60 rounded-3xl"/>:error?<p>Não foi possível carregar as solicitações.</p>:<div className="grid gap-4">{data.map(row=><article key={row.id} className="rounded-3xl border border-border bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-lg">{row.name}</strong><p className="text-sm text-foreground/60">{new Date(row.created_at).toLocaleString('pt-BR')} · {row.whatsapp} · {row.email||'Sem e-mail'}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${row.contacted?'bg-green-100 text-green-800':'bg-muted'}`}>{row.contacted?'Contatado':'Pendente'}</span></div><p className="mt-4 text-sm">{'brand' in row?`${row.brand} ${row.model} · ${row.year} · ${row.mileage} km · R$ ${row.asking_price}`:`${row.vehicle_text||'Veículo não especificado'} · ${row.installments} parcelas`}</p>{'notes' in row&&row.notes&&<p className="mt-2 text-sm text-foreground/65">{row.notes}</p>}{'sell_request_photos' in row&&row.sell_request_photos.length>0&&<div className="mt-4 flex flex-wrap gap-2">{row.sell_request_photos.map(photo=><LeadPhoto key={photo.id} path={photo.storage_path}/>)}</div>}<div className="mt-5 flex flex-wrap gap-3"><a className="btn-primary" href={`https://wa.me/${digits(row.whatsapp)}`} target="_blank" rel="noopener noreferrer">Abrir WhatsApp</a><button className="btn-outline" onClick={()=>mark(row.id,row.contacted)}>{row.contacted?'Marcar pendente':'Marcar contatado'}</button><button className="btn-outline text-accent" onClick={()=>remove(row.id)}>Excluir</button></div></article>)}{data.length===0&&<p className="rounded-3xl bg-card p-8">Nenhuma solicitação por enquanto.</p>}</div>}</>
}
function LeadPhoto({path}:{path:string}){const {data}=useQuery({queryKey:['lead-photo',path],queryFn:async()=>{const {data,error}=await supabase.storage.from('sell-requests').createSignedUrl(path,3600);if(error)throw error;return data.signedUrl},staleTime:300000});return data?<a href={data} target="_blank" rel="noopener noreferrer"><img src={data} alt="Foto enviada pelo cliente" width="110" height="90" className="h-20 w-28 rounded-xl object-cover"/></a>:<div className="skeleton h-20 w-28 rounded-xl"/>}
